# Generated by Django 5.2.14 on 2026-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedvideo',
            name='video_id',
            field=models.CharField(default='temp', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processedvideo',
            name='youtube_url',
            field=models.URLField(),
        ),
    ]
