# Generated by Django 5.2.14 on 2026-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0002_processedvideo_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedvideo',
            name='final_video_path',
        ),
        migrations.AddField(
            model_name='processedvideo',
            name='transcript_segments',
            field=models.JSONField(default='empt'),
            preserve_default=False,
        ),
    ]
