# Generated by Django 5.2.14 on 2026-05-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0003_remove_processedvideo_final_video_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('youtube_url', models.URLField()),
                ('final_video', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
